[general]
import = [
        "~/.config/alacritty/Themes/catppuccin_macchiato.toml"
]

[env]
term = "alacritty"

[font]
size = 10

normal = {family = "ComicShannsMono Nerd Font", style = "Regular"}
bold = {family = "ComicShannsMono Nerd Font", style = "Bold"}
italic = {family = "ComicShannsMono Nerd Font", style = "Italic"}
bold_italic = {family = "ComicShannsMono Nerd Font", style = "Bold Italic"}

[window]
padding = {x = 8, y = 8}

class = { instance = "Alacritty", general = "Alacritty" }

[mouse]
hide_when_typing = true
