#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

sh ~/.config/bspwm/autostart

nm-applet &
dunst &
polkit &
xset -dpms s off &

feh --bg-scale ~/Downloads/Telegram\ Desktop/nvim.png

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width        2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#d65d0e"
bspc config normal_border_color "#282828"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
