import bpy
import os

def kmi_props_setattr(kmi_props, attr, value):
    try:
        setattr(kmi_props, attr, value)
    except AttributeError:
        print("Warning: property '%s' not found in keymap item '%s'" %
              (attr, kmi_props.__class__.__name__))
    except Exception as e:
        print("Warning: %r" % e)

wm = bpy.context.window_manager
kc = wm.keyconfigs.new(os.path.splitext(os.path.basename(__file__))[0])

# Map View3D Fly Modal
km = kc.keymaps.new('View3D Fly Modal', space_type='EMPTY', region_type='WINDOW', modal=True)

kmi = km.keymap_items.new_modal('CANCEL', 'ESC', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('CANCEL', 'RIGHTMOUSE', 'ANY', any=True)
kmi = km.keymap_items.new_modal('CONFIRM', 'LEFTMOUSE', 'ANY', any=True)
kmi = km.keymap_items.new_modal('CONFIRM', 'RET', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('CONFIRM', 'SPACE', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('CONFIRM', 'NUMPAD_ENTER', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('ACCELERATE', 'NUMPAD_PLUS', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('DECELERATE', 'NUMPAD_MINUS', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('ACCELERATE', 'WHEELUPMOUSE', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('DECELERATE', 'WHEELDOWNMOUSE', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('CANCEL', 'TRACKPADPAN', 'ANY')
kmi = km.keymap_items.new_modal('PAN_ENABLE', 'MIDDLEMOUSE', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('PAN_DISABLE', 'MIDDLEMOUSE', 'RELEASE', any=True)
kmi = km.keymap_items.new_modal('FORWARD', 'W', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('BACKWARD', 'R', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('LEFT', 'A', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('RIGHT', 'S', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('UP', 'F', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('DOWN', 'Q', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('UP', 'R', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('DOWN', 'F', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('FORWARD', 'UP_ARROW', 'PRESS')
kmi = km.keymap_items.new_modal('BACKWARD', 'DOWN_ARROW', 'PRESS')
kmi = km.keymap_items.new_modal('LEFT', 'LEFT_ARROW', 'PRESS')
kmi = km.keymap_items.new_modal('RIGHT', 'RIGHT_ARROW', 'PRESS')
kmi = km.keymap_items.new_modal('AXIS_LOCK_X', 'X', 'PRESS')
kmi = km.keymap_items.new_modal('AXIS_LOCK_Z', 'Z', 'PRESS')
kmi = km.keymap_items.new_modal('PRECISION_ENABLE', 'LEFT_ALT', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('PRECISION_DISABLE', 'LEFT_ALT', 'RELEASE', any=True)
kmi = km.keymap_items.new_modal('PRECISION_ENABLE', 'LEFT_SHIFT', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('PRECISION_DISABLE', 'LEFT_SHIFT', 'RELEASE', any=True)
kmi = km.keymap_items.new_modal('FREELOOK_ENABLE', 'LEFT_CTRL', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('FREELOOK_DISABLE', 'LEFT_CTRL', 'RELEASE', any=True)

# Map View3D Walk Modal
km = kc.keymaps.new('View3D Walk Modal', space_type='EMPTY', region_type='WINDOW', modal=True)

kmi = km.keymap_items.new_modal('CANCEL', 'ESC', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('CANCEL', 'RIGHTMOUSE', 'ANY', any=True)
kmi = km.keymap_items.new_modal('CONFIRM', 'LEFTMOUSE', 'ANY', any=True)
kmi = km.keymap_items.new_modal('CONFIRM', 'RET', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('CONFIRM', 'NUMPAD_ENTER', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('FAST_ENABLE', 'LEFT_SHIFT', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('FAST_DISABLE', 'LEFT_SHIFT', 'RELEASE', any=True)
kmi = km.keymap_items.new_modal('SLOW_ENABLE', 'LEFT_ALT', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('SLOW_DISABLE', 'LEFT_ALT', 'RELEASE', any=True)
kmi = km.keymap_items.new_modal('FORWARD', 'W', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('BACKWARD', 'R', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('LEFT', 'A', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('RIGHT', 'S', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('UP', 'F', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('DOWN', 'Q', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('FORWARD_STOP', 'W', 'RELEASE', any=True)
kmi = km.keymap_items.new_modal('BACKWARD_STOP', 'R', 'RELEASE', any=True)
kmi = km.keymap_items.new_modal('LEFT_STOP', 'A', 'RELEASE', any=True)
kmi = km.keymap_items.new_modal('RIGHT_STOP', 'S', 'RELEASE', any=True)
kmi = km.keymap_items.new_modal('UP_STOP', 'F', 'RELEASE', any=True)
kmi = km.keymap_items.new_modal('DOWN_STOP', 'Q', 'RELEASE', any=True)
kmi = km.keymap_items.new_modal('FORWARD', 'UP_ARROW', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('BACKWARD', 'DOWN_ARROW', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('LEFT', 'LEFT_ARROW', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('RIGHT', 'RIGHT_ARROW', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('FORWARD_STOP', 'UP_ARROW', 'RELEASE', any=True)
kmi = km.keymap_items.new_modal('BACKWARD_STOP', 'DOWN_ARROW', 'RELEASE', any=True)
kmi = km.keymap_items.new_modal('LEFT_STOP', 'LEFT_ARROW', 'RELEASE', any=True)
kmi = km.keymap_items.new_modal('RIGHT_STOP', 'RIGHT_ARROW', 'RELEASE', any=True)
kmi = km.keymap_items.new_modal('GRAVITY_TOGGLE', 'TAB', 'PRESS')
kmi = km.keymap_items.new_modal('GRAVITY_TOGGLE', 'G', 'PRESS')
kmi = km.keymap_items.new_modal('JUMP', 'V', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('JUMP_STOP', 'V', 'RELEASE', any=True)
kmi = km.keymap_items.new_modal('TELEPORT', 'SPACE', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('TELEPORT', 'MIDDLEMOUSE', 'ANY', any=True)
kmi = km.keymap_items.new_modal('ACCELERATE', 'NUMPAD_PLUS', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('DECELERATE', 'NUMPAD_MINUS', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('ACCELERATE', 'WHEELUPMOUSE', 'PRESS', any=True)
kmi = km.keymap_items.new_modal('DECELERATE', 'WHEELDOWNMOUSE', 'PRESS', any=True)

