#!/bin/sh

killall picom 
killall polybar 
killall dunst

redshift -x 

killall redshift

while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
while pgrep -u $UID -x redshift >/dev/null; do sleep 1; done
while pgrep -u $UID -x dunst >/dev/null; do sleep 1; done

picom --vsync &

redshift &

otd-daemon &

polybar -r root &

dunst &
