#!/bin/sh

eww kill &

redshift -x 

killall -9 redshift

killall picom 

while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
while pgrep -u $UID -x eww >/dev/null; do sleep 1; done
while pgrep -u $UID -x redshift >/dev/null; do sleep 1; done

picom &

redshift &

otd-daemon &

eww daemon &
# sleep 0.3
eww open barleft1 &
# polybar -r root | tee /tmp/polybar.log & disown 
