#!/bin/sh

export NET_ROOT="$HOME/.dotnet"

redshift -x 
killall -9 redshift
eww kill &

while pgrep -u $UID -x eww >/dev/null; do sleep 1; done
eww open barleft1 &

otd-daemon &

while pgrep -u $UID -x redshift >/dev/null; do sleep 1; done
redshift &
