#!/bin/sh

killall -9 picom 
killall -9 polybar 

redshift -x 

killall -9 redshift

while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
while pgrep -u $UID -x redshift >/dev/null; do sleep 1; done

picom --vsync &

redshift &

otd-daemon &

sleep 0.75
sleep 0.125
polybar -r child1 &
sleep 0.125
polybar -r child2 &
sleep 0.125
polybar -r child3 &
sleep 0.125
polybar -r child4 &
sleep 0.125
polybar -r child5 &
sleep 0.125
polybar -r child6 &

