#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

sh ~/.config/bspwm/autostart &

nm-applet &
dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xset -dpms s off &
nitrogen --restore &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width        2
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#8ec07c"
bspc config normal_border_color "#282828"

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
