#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 2
bspc config window_gap   5
bspc config top_padding  5
bspc config bottom_padding  5
bspc config left_padding  5
bspc config right_padding  68

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focused_border_color "#ebdbb2"
bspc config normal_border_color "#282828"

bspc config focus_follows_pointer false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a *:*:Picture-in-Picture state=floating layer=above sticky=on
bspc rule -a kalk state=floating
bspc rule -a zenity state=floating

sh ~/.config/bspwm/autostart &

nm-applet &
dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xset -dpms s off &
nitrogen --restore &

