[font]
size = 11.25

builtin_box_drawing = true

[font.normal]
family = "FantasqueSansM Nerd Font"

[font.bold]
family = "FantasqueSansM Nerd Font"

[font.italic]
family = "FantasqueSansM Nerd Font"

[font.bold_italic]
family = "FantasqueSansM Nerd Font"

[font.offset]
x = 0
y = 0
[font.glyph_offset]
x = 0
y = 0
