[font]
size = 10

builtin_box_drawing = true

[font.normal]
family = "Mononoki Nerd Font"

[font.bold]
family = "Mononoki Nerd Font"

[font.italic]
family = "Monooki Nerd Font"

[font.bold_italic]
family = "Mononoki Nerd Font"

[font.offset]
x = 0
y = 0
[font.glyph_offset]
x = 0
y = 0
